name: Publish NuGet

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish PGLN.Auth
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Display .NET information
        run: dotnet --info

      - name: Restore
        run: dotnet restore PGLN.Auth.slnx

      - name: Build
        run: >
          dotnet build PGLN.Auth.slnx
          --configuration Release
          --no-restore

      - name: Test
        run: >
          dotnet test PGLN.Auth.slnx
          --configuration Release
          --no-build
          --no-restore

      - name: Authenticate to NuGet
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: Nathi-devDot